name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        image:
          - lt1.2-latest
          - lt2-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make -f docker/Makefile torrest-dev IMAGE_TAG="${{ matrix.image }}"
      - name: Upload torrest artifact
        uses: actions/upload-artifact@v2
        with:
          name: torrest-linux-x64-debug-${{ matrix.image }}
          path: build/dev/torrest
