name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir cmake-build
          docker run --rm -v "$(pwd):/build" -w "/build" i96751414/libtorrent-cpp:latest \
            cmake --build cmake-build --target torrest

      - name: Upload torrest artifact
        uses: actions/upload-artifact@v2
        with:
          path: cmake-build/torrest
