name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker run --rm -v "$(pwd):/build" -w "/build" i96751414/libtorrent-cpp:latest bash -c '\
            cmake -B cmake-build -DCMAKE_BUILD_TYPE=Debug && \
            cmake --build cmake-build --target torrest -- -j "$(nproc)" \
          '

      - name: Upload torrest artifact
        uses: actions/upload-artifact@v2
        with:
          name: torrest-linux-x64-debug
          path: cmake-build/torrest
