name: build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make -f docker/Makefile torrest-dev
      - name: Upload torrest artifact
        uses: actions/upload-artifact@v2
        with:
          name: torrest-linux-x64-debug
          path: build/dev/torrest
