name: cross-build
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Image tags (space delimited)"
        default: "latest"
        required: true
        type: string
      push:
        description: "Push built images"
        default: false
        type: boolean
      libtorrent-version:
        description: "Libtorrent version (empty for default)"
        default: ""
        required: false
        type: string
jobs:
  cross-build:
    name: "Build cross compiler"
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      matrix:
        platform:
          - linux-armv7
          - linux-arm64
          - linux-x64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ${{ matrix.platform }} docker image
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.libtorrent-version }}" ]; then
            echo "Setting libtorrent version to ${{ github.event.inputs.libtorrent-version }}"
            sed -i "s|\(LIBTORRENT_VERSION=\).*|\1${{ github.event.inputs.libtorrent-version }}|g" scripts/versions.env
          fi
          for tag in ${{ github.event.inputs.tags }}; do
            make -f docker/Makefile build-${{ matrix.platform }} IMAGE_TAG=${tag}
          done

      - name: Login to Docker Hub
        if: success() && github.event.inputs.push == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push ${{ matrix.platform }} docker image
        if: success() && github.event.inputs.push == 'true'
        shell: bash
        run: |
          for tag in ${{ github.event.inputs.tags }}; do
            make -f docker/Makefile push-${{ matrix.platform }} IMAGE_TAG=${tag}
          done
