name: full-build
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 5
      matrix:
        platform:
          - android-arm
          - android-arm64
          - android-x64
          - android-x86
          - darwin-x64
          - linux-armv7
          - linux-arm64
          - linux-x64
          - linux-x86
          - windows-x64
          - windows-x86
        target:
          - torrest
          - libtorrest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ${{ matrix.target }} (${{ matrix.platform }})
        run: make -f docker/Makefile ${{ matrix.target }}-${{ matrix.platform }} IMAGE_TAG=lt1.2-latest

      - name: Generate ${{ matrix.target }} (${{ matrix.platform }}) zip
        id: generate_zip
        run: |
          make -f docker/Makefile zip-${{ matrix.target }}-${{ matrix.platform }}
          asset_path="$(ls build/binaries/*.zip)"
          echo "asset_path=${asset_path}" >>"${GITHUB_OUTPUT}"
          echo "asset_name=$(basename "${asset_path}")" >>"${GITHUB_OUTPUT}"

      - name: Upload ${{ matrix.target }} (${{ matrix.platform }}) zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-${{ matrix.platform }}
          path: ${{ steps.generate_zip.outputs.asset_path }}

  release:
    name: Release
    needs: build-artifacts
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Perform release
        run: |
          git_tag="$(sed 's|refs/tags/||' <<< "${{ github.ref }}")"
          changelog="$(awk '/^## /{ if (p) exit; p=1; next } p' CHANGELOG.md)"
          gh release create "${git_tag}" artifacts/*/*.zip --notes "${changelog}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
