name: release
on:
  create:
    tags:
      - '*'
jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        platform:
          - android-arm
          - android-arm64
          - android-x64
          - android-x86
          - darwin-x64
          - linux-armv7
          - linux-arm64
          - linux-x64
          - linux-x86
          - windows-x64
          - windows-x86
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build ${{ matrix.platform }}
        run: make -f docker/Makefile torrest-${{ matrix.platform }}

      - name: Generate ${{ matrix.platform }} zip
        id: generate_zip
        run: |
          make -f docker/Makefile zip-${{ matrix.platform }}
          asset_path=$(ls build/binaries/*.zip)
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=asset_name::$(basename "${asset_path}")"

      - name: Upload ${{ matrix.platform }} zip
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: ${{ steps.generate_zip.outputs.asset_path }}

  release:
    name: Release
    needs: build-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Perform release
        run: |
          assets=()
          for asset in artifacts/*/*.zip; do
            assets+=("-a" "${asset}")
          done
          git_tag="$(sed 's|refs/tags/||' <<< "${{ github.ref }}")"
          hub release create "${assets[@]}" -m "${git_tag}" "${git_tag}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
